import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
    en: {
        // Navbar
        findJobs: 'Find Jobs',
        internships: 'Internships',
        skillGap: 'Skill Gap',
        forEmployers: 'For Employers',
        kioskMode: 'Kiosk Mode',
        startLearning: 'Start Learning',
        logout: 'Logout',
        login: 'Login',
        register: 'Register',
        
        // Jobs
        jobsTitle: 'Find Your Perfect Job',
        jobsDescription: 'AI-matched opportunities based on your verified profile.',
        searchJobs: 'Search jobs by title, skill, or company...',
        uploadResumePrompt: 'Upload resume to see personalized match scores',
        uploadNow: 'Upload Now',
        noJobsFound: 'No jobs found matching your search',
        whyMatch: 'Why you match:',
        missing: 'Missing',
        uploadForMatch: 'Upload for match',
        trustedEmployer: 'Trusted Employer',
        applyNow: 'Apply Now',
        details: 'Details',
        
        // Internships
        internshipsTitle: 'Find Your Dream Internship',
        internshipsDescription: 'Gain real-world experience and kickstart your career',
        domain: 'Domain',
        allDomains: 'All Domains',
        location: 'Location',
        allLocations: 'All Locations',
        internshipType: 'Internship Type',
        allTypes: 'All Types',
        paid: 'Paid',
        unpaid: 'Unpaid',
        stipend: 'Stipend',
        applicants: 'Applicants',
        posted: 'Posted',
        noInternshipsFound: 'No internships found',
        adjustFilters: 'Try adjusting your filters to see more results',
        applyFilters: 'Apply Filters',
        
        // Common
        filters: 'Filters',
        clearFilters: 'Clear Filters',
        resetFilters: 'Reset Filters',
        salary: 'Salary',
        minimumSalary: 'Minimum Salary',
        company: 'Company',
        type: 'Type',
        jobType: 'Job Type',
        fullTime: 'Full Time',
        partTime: 'Part Time',
        contract: 'Contract',
        gig: 'Gig',
        remote: 'Remote',
        onsite: 'On-site',
        hybrid: 'Hybrid',
        
        // Landing Page
        heroTagline: 'Connecting Talent to Opportunity',
        heroTitle1: 'Get Hired. Get Verified.',
        heroTitle2: 'Get Ahead.',
        heroSubtitle: "India's first blockchain-verified employment platform for rural talent. Connect with top employers and prove your skills instantly.",
        jobSeeker: "I'm a Job Seeker",
        startLearningNow: 'Start Learning Now',
        governmentVerified: 'Government Verified',
        candidates10L: '10L+ Candidates',
        youthUnaware: 'Youth unaware of matching jobs',
        verifiedProfiles: 'Verified Profiles',
        corporatePartners: 'Corporate Partners',
        whyChoose: 'Why Choose SkillBridge?',
        bridgingGap: 'Bridging the gap between talent and opportunity.',
        verifiedCredentialsTitle: 'Verified Credentials',
        verifiedCredentialsDesc: 'Your skills and education are verified on the blockchain. No more fake resumes.',
        skillGapAnalysisTitle: 'Skill-Gap Analysis',
        skillGapAnalysisDesc: 'Find out exactly what skills you need to get your dream job with our AI assessment.',
        instantMatchingTitle: 'Instant Matching',
        instantMatchingDesc: 'Our AI matches you with jobs that fit your profile perfectly. Apply with one click.',
        microLearningTitle: 'Master Skills with Micro Learning',
        microLearningSubtitle: 'Learn new skills in bite-sized lessons. Master the basics in minutes, not hours.',
        lessonDuration: '5-15 Minute Lessons',
        lessonDurationDesc: 'Short, focused lessons that fit into your busy schedule',
        techModules: '22+ Tech Modules',
        techModulesDesc: 'AI, Machine Learning, Web Dev, Cybersecurity & More',
        earnBadges: 'Earn Points & Badges',
        earnBadgesDesc: 'Track your progress and showcase your achievements',
        freeSelfPaced: 'Free • Self-paced • Certificate Ready',
        readyCareer: 'Ready to start your career journey?',
        joinThousands: 'Join thousands of others securing their future today.',
        goToDashboard: 'Go to Dashboard',
        createProfile: 'Create Free Profile',
        opportunitiesNear: 'Opportunities near you',
        studentTitle: 'I want to be a...',
        student: 'Student',
        selectInterest: 'Select Interest Area',
        interestHint: 'Interest areas like Automotive, Electronics etc.',
        findCourse: 'FIND COURSE',
        exploreTitle: 'I want to explore...',
        opportunities: 'Opportunities',
        searchJobExchange: 'Search Job Exchange',
        opportunitiesHint: 'Opportunities for Job Exchange, Apprenticeship and Entrepreneurship',
        findJob: 'FIND JOB',
        notSure: 'Not Sure',
        whereBegin: 'Where To Begin?',
        guidanceSubtitle: 'Answer a few simple questions and we will help you.',
        educationLevelQuestion: 'What is your highest education level?',
        selectEducation: 'Select Education',
        next: 'NEXT',
        
        // Login & Auth
        welcomeBack: 'Welcome Back',
        loginSubtitle: 'Login to access your verified profile',
        email: 'Email',
        password: 'Password',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot Password?',
        loginButton: 'Login',
        noAccount: "Don't have an account?",
        signUp: 'Sign Up',
        getStarted: 'Get Started with SkillBridge',
        registerNow: 'Register Now',
        alreadyHaveAccount: 'Already have an account?',
        name: 'Full Name',
        phone: 'Phone Number',
        confirmPassword: 'Confirm Password',
        iAgree: 'I agree to',
        termsAndConditions: 'Terms and Conditions',
        and: 'and',
        privacyPolicy: 'Privacy Policy',
        
        // Dashboard
        welcome: 'Welcome',
        welcomeBack2: 'Welcome back',
        dashboard: 'Dashboard',
        careerProgress: 'Here is your career progress today',
        profileCompletion: 'Profile Completion',
        complete: 'Complete',
        topJobMatches: 'Top Job Matches',
        viewAllJobs: 'View All Jobs',
        myCredentials: 'My Credentials',
        recentActivity: 'Recent Activity',
        recommendedForYou: 'Recommended For You',
        skillsOverview: 'Skills Overview',
        viewSkillGap: 'View Skill Gap',
        
        // Profile Setup
        profileSetupTitle: 'Complete Your Profile',
        profileSetupSubtitle: 'Tell us about yourself to get personalized job matches',
        personalInformation: 'Personal Information',
        contactInformation: 'Contact Information',
        address: 'Address',
        city: 'City',
        state: 'State',
        pincode: 'Pincode',
        education: 'Education',
        highestQualification: 'Highest Qualification',
        fieldOfStudy: 'Field of Study',
        institution: 'Institution',
        yearOfPassing: 'Year of Passing',
        skills: 'Skills',
        addSkills: 'Add Your Skills',
        experience: 'Experience',
        yearsOfExperience: 'Years of Experience',
        currentCompany: 'Current Company',
        jobTitle: 'Job Title',
        saveChanges: 'Save Changes',
        cancel: 'Cancel',
        skip: 'Skip',
        skipForNow: 'Skip for Now',
        back: 'Back',
        continue: 'Continue',
        
        // Resume Upload
        uploadResume: 'Upload Resume',
        uploadResumeTitle: 'Upload Your Resume',
        uploadResumeSubtitle: 'Upload your resume in PDF format for AI-powered skill analysis and personalized recommendations.',
        chooseFile: 'Choose PDF file',
        dragDropHere: 'or drag and drop here',
        maxFileSize: 'Max file size: 5MB',
        changeFile: 'Change File',
        resumeUploadedSuccess: 'Resume uploaded successfully!',
        analyzingResume: 'Analyzing your resume with AI...',
        dragDropResume: 'Drag and drop your resume here',
        or: 'or',
        browseFiles: 'Browse Files',
        fileRequirements: 'Supported formats: PDF (Max 5MB)',
        uploading: 'Uploading',
        analyzing: 'Analyzing',
        uploadSuccess: 'Resume uploaded successfully!',
        uploadFailed: 'Resume upload failed',
        analysisComplete: 'Analysis Complete',
        uploadAndAnalyze: 'Upload & Analyze',
        uploaded: 'Uploaded',
        skipForNowBtn: 'Skip for Now',
        whatHappensNext: 'What happens next?',
        securelyStored: 'Your resume is securely stored in Firebase Storage',
        aiAnalyzes: 'AI analyzes your skills, experience, and education',
        personalizedRecommendations: 'Get personalized job recommendations and skill gap analysis',
        encryptedSecure: 'Your data is encrypted and securely stored',
        
        // Learning/Micro Learning
        learningTitle: 'Micro Learning',
        learningSubtitle: 'Learn new skills in bite-sized lessons',
        allCourses: 'All Courses',
        inProgress: 'In Progress',
        completed: 'Completed',
        startCourse: 'Start Course',
        continueLearning: 'Continue Learning',
        lessons: 'Lessons',
        duration: 'Duration',
        difficulty: 'Difficulty',
        beginner: 'Beginner',
        intermediate: 'Intermediate',
        advanced: 'Advanced',
        enrollNow: 'Enroll Now',
        certificateAvailable: 'Certificate Available',
        
        // Employer Dashboard
        employerPortal: 'Employer Portal',
        employerSubtitle: 'Find and hire verified rural talent',
        postJob: 'Post a Job',
        activeJobs: 'Active Jobs',
        totalApplicants: 'Total Applicants',
        interviewed: 'Interviewed',
        hired: 'Hired',
        recentApplicants: 'Recent Applicants',
        searchCandidates: 'Search Candidates',
        viewProfile: 'View Profile',
        scheduleInterview: 'Schedule Interview',
        shortlist: 'Shortlist',
        match: 'Match',
        
        // Common Buttons & Actions
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        confirm: 'Confirm',
        yes: 'Yes',
        no: 'No',
        ok: 'OK',
        close: 'Close',
        submit: 'Submit',
        apply: 'Apply',
        download: 'Download',
        share: 'Share',
        viewDetails: 'View Details',
        viewAll: 'View All',
        learnMore: 'Learn More',
        search: 'Search',
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        tryAgain: 'Try Again',
        goBack: 'Go Back',
        
        // Messages
        noDataAvailable: 'No data available',
        somethingWentWrong: 'Something went wrong',
        pleaseWait: 'Please wait...',
        processingRequest: 'Processing your request...',
        savedSuccessfully: 'Saved successfully',
        updatedSuccessfully: 'Updated successfully',
        deletedSuccessfully: 'Deleted successfully',
        
        // Skill Gap Dashboard
        skillGapDashboardTitle: 'Skill Gap Analysis Dashboard',
        aiWorkforceInsights: 'AI-powered workforce skill insights',
        reseedDemoData: 'Reseed Demo Data',
        seeding: 'Seeding...',
        menu: 'MENU',
        resumeAnalysis: 'Resume Analysis',
        analyzed: 'Analyzed',
        empty: 'Empty',
        noResumeAnalysisFound: 'No Resume Analysis Found',
        uploadResumeUnlock: 'Upload your resume to unlock AI-powered skill insights and personalized career recommendations.',
        resumeScore: 'Resume Score',
        experienceLevel: 'Experience',
        detailedAnalysisResults: 'Detailed Analysis Results',
        skillMatchingFor: 'Skill matching for',
        selectedRole: 'Selected Role',
        matchPercentage: 'Match Percentage',
        requiredSkillsPossessed: 'Required Skills possessed',
        readinessScore: 'Readiness Score',
        outOf100: 'Out of 100 points',
        gapOverview: 'Gap Overview',
        critical: 'Critical',
        moderate: 'Moderate',
        good: 'Good',
        skillName: 'Skill Name',
        required: 'Required',
        user: 'User',
        status: 'Status',
        recommendedLearningAI: 'Recommended Learning (AI Powered)',
        personalizedTutorials: 'Personalized tutorials based on your skills',
        curatingVideos: 'Curating personalized videos...',
        watchNow: 'Watch Now',
        tutorial: 'Tutorial',
        noVideoRecommendations: 'No video recommendations found. Upload your resume to unlock personalized learning paths.',
        profileOverview: 'Profile Overview',
        lastUpdated: 'Last Updated',
        resumeStatus: 'Resume Status',
        verified: 'Verified',
        pendingUpload: 'Pending Upload',
        skillScore: 'Skill Score',
        matchStrength: 'Match Strength',
        quickActions: 'Quick Actions',
        uploadResumeBtn: 'Upload Resume',
        viewSkillGapReport: 'View Skill Gap Report',
        exploreCourses: 'Explore Courses',
        tip: 'Tip',
        completeCriticalSkills: 'Complete the critical skill gaps highlighted in your profile to increase your match strength by up to 40%.',
        authenticating: 'Authenticating...',
        loadingDashboard: 'Loading dashboard...',
        
        // Resume Upload Page
        chooseFile: 'Choose PDF file',
        dragDropHere: 'or drag and drop here',
        maxFileSize: 'Max file size: 5MB',
        changeFile: 'Change File',
        analyzingResume: 'Analyzing your resume with AI...',
        resumeUploadedSuccess: 'Resume uploaded successfully!',
        skipForNowBtn: 'Skip for Now',
        encryptedSecure: 'Your data is encrypted and securely stored',
        
        // Profile Setup
        interestedDomain: 'Interested Domain',
        selectDomain: 'Select your desired job role',
        selectSkills: 'Select Your Skills',
        selectSkillsHint: 'Choose skills you have or want to learn',
        fieldOfInterest: 'Field of Interest',
        enterFieldInterest: 'Enter your specific field of interest',
        experienceLevelLabel: 'Experience Level',
        selectExperienceLevel: 'Select your experience level',
        locationLabel: 'Preferred Location',
        selectLocation: 'Select preferred work location',
        fresher: 'Fresher',
        junior: 'Junior',
        midLevel: 'Mid-Level',
        senior: 'Senior',
        
        // Basic Info
        fullName: 'Full Name',
        phoneNumber: 'Phone Number',
        dateOfBirth: 'Date of Birth',
        gender: 'Gender',
        male: 'Male',
        female: 'Female',
        other: 'Other',
        district: 'District',
        selectDistrict: 'Select District',
        selectState: 'Select State',
        selectGender: 'Select Gender',
        basicInfoTitle: 'Basic Information',
        basicInfoSubtitle: 'Please provide your personal details',
        
        // Validation Messages
        nameRequired: 'Full name is required',
        nameMinLength: 'Name must be at least 3 characters',
        phoneRequired: 'Phone number is required',
        invalidPhone: 'Enter a valid 10-digit Indian mobile number',
        invalidEmail: 'Enter a valid email address',
        dobRequired: 'Date of birth is required',
        ageRestriction: 'Age must be between 18 and 100 years',
        genderRequired: 'Please select your gender',
        stateRequired: 'Please select your state',
        districtRequired: 'District is required',
        domainRequired: 'Please select your interested domain',
        skillsRequired: 'Please select at least one skill',
        fieldRequired: 'Please enter your field of interest'
    },
    ta: {
        // Navbar
        findJobs: 'வேலைகளை கண்டறியவும்',
        internships: 'பயிற்சி வாய்ப்புகள்',
        skillGap: 'திறன் இடைவெளி',
        forEmployers: 'முதலாளிகளுக்கு',
        kioskMode: 'கியோஸ்க் முறை',
        startLearning: 'கற்றல் தொடங்கு',
        logout: 'வெளியேறு',
        login: 'உள்நுழை',
        register: 'பதிவு செய்',
        
        // Jobs
        jobsTitle: 'உங்கள் சரியான வேலையை கண்டறியவும்',
        jobsDescription: 'உங்கள் சரிபார்க்கப்பட்ட சுயவிவரத்தின் அடிப்படையில் AI-பொருத்தப்பட்ட வாய்ப்புகள்.',
        searchJobs: 'தலைப்பு, திறன் அல்லது நிறுவனம் மூலம் வேலைகளைத் தேடுங்கள்...',
        uploadResumePrompt: 'தனிப்பயனாக்கப்பட்ட பொருத்த மதிப்பெண்களைக் காண ரெஸ்யூமை பதிவேற்றவும்',
        uploadNow: 'இப்போது பதிவேற்றவும்',
        noJobsFound: 'உங்கள் தேடலுடன் பொருந்தும் வேலைகள் இல்லை',
        whyMatch: 'நீங்கள் ஏன் பொருந்துகிறீர்கள்:',
        missing: 'விடுபட்டது',
        uploadForMatch: 'பொருத்தத்திற்கு பதிவேற்றவும்',
        trustedEmployer: 'நம்பகமான முதலாளி',
        applyNow: 'இப்போது விண்ணப்பிக்கவும்',
        details: 'விவரங்கள்',
        
        // Internships
        internshipsTitle: 'உங்கள் கனவு பயிற்சியை கண்டறியவும்',
        internshipsDescription: 'நிஜ உலக அனுபவத்தைப் பெறுங்கள் மற்றும் உங்கள் வாழ்க்கையைத் தொடங்குங்கள்',
        domain: 'களம்',
        allDomains: 'அனைத்து களங்கள்',
        location: 'இடம்',
        allLocations: 'அனைத்து இடங்கள்',
        internshipType: 'பயிற்சி வகை',
        allTypes: 'அனைத்து வகைகள்',
        paid: 'ஊதியம்',
        unpaid: 'ஊதியம் இல்லை',
        stipend: 'உதவித்தொகை',
        applicants: 'விண்ணப்பதாரர்கள்',
        posted: 'வெளியிடப்பட்டது',
        noInternshipsFound: 'பயிற்சிகள் கிடைக்கவில்லை',
        adjustFilters: 'மேலும் முடிவுகளைப் பார்க்க உங்கள் வடிப்பான்களைச் சரிசெய்யவும்',
        applyFilters: 'வடிப்பான்களைப் பயன்படுத்து',
        
        // Common
        filters: 'வடிப்பான்கள்',
        clearFilters: 'வடிப்பான்களை அழி',
        resetFilters: 'வடிப்பான்களை மீட்டமை',
        salary: 'சம்பளம்',
        minimumSalary: 'குறைந்தபட்ச சம்பளம்',
        company: 'நிறுவனம்',
        type: 'வகை',
        jobType: 'வேலை வகை',
        fullTime: 'முழு நேரம்',
        partTime: 'பகுதி நேரம்',
        contract: 'ஒப்பந்தம்',
        gig: 'குறுகிய வேலை',
        remote: 'தொலைநிலை',
        onsite: 'அலுவலகத்தில்',
        hybrid: 'கலப்பு',
        
        // Landing Page
        heroTagline: 'திறமையை வாய்ப்புடன் இணைக்கிறோம்',
        heroTitle1: 'வேலை பெறுங்கள். சரிபார்க்கப்படுங்கள்.',
        heroTitle2: 'முன்னேறுங்கள்.',
        heroSubtitle: 'கிராமப்புற திறமைகளுக்கான இந்தியாவின் முதல் பிளாக்செயின்-சரிபார்க்கப்பட்ட வேலைவாய்ப்பு தளம். சிறந்த முதலாளிகளுடன் இணையுங்கள் மற்றும் உங்கள் திறன்களை உடனடியாக நிரூபியுங்கள்.',
        jobSeeker: 'நான் வேலை தேடுபவர்',
        startLearningNow: 'இப்போதே கற்றல் தொடங்குங்கள்',
        governmentVerified: 'அரசு சரிபார்க்கப்பட்டது',
        candidates10L: '10L+ வேட்பாளர்கள்',
        youthUnaware: 'பொருந்தும் வேலைகள் குறித்து இளைஞர்கள் அறியாதவர்கள்',
        verifiedProfiles: 'சரிபார்க்கப்பட்ட சுயவிவரங்கள்',
        corporatePartners: 'கார்ப்பரேட் பங்குதாரர்கள்',
        whyChoose: 'ஏன் SkillBridge ஐ தேர்வு செய்ய வேண்டும்?',
        bridgingGap: 'திறமை மற்றும் வாய்ப்புக்கு இடையிலான இடைவெளியைக் குறைக்கிறது.',
        verifiedCredentialsTitle: 'சரிபார்க்கப்பட்ட சான்றுகள்',
        verifiedCredentialsDesc: 'உங்கள் திறன்கள் மற்றும் கல்வி பிளாக்செயினில் சரிபார்க்கப்படுகின்றன. போலி ரெஸ்யூம்கள் இல்லை.',
        skillGapAnalysisTitle: 'திறன் இடைவெளி பகுப்பாய்வு',
        skillGapAnalysisDesc: 'உங்கள் கனவு வேலையைப் பெற நீங்கள் என்ன திறன்கள் தேவை என்பதை AI மதிப்பீட்டின் மூலம் அறியுங்கள்.',
        instantMatchingTitle: 'உடனடி பொருத்தம்',
        instantMatchingDesc: 'எங்கள் AI உங்கள் சுயவிவரத்துடன் சரியாகப் பொருந்தும் வேலைகளை பொருத்துகிறது. ஒரே கிளிக்கில் விண்ணப்பிக்கவும்.',
        microLearningTitle: 'மைக்ரோ கற்றல் மூலம் திறன்களை மாஸ்டர் செய்யுங்கள்',
        microLearningSubtitle: 'சிறிய பாடங்களில் புதிய திறன்களைக் கற்றுக்கொள்ளுங்கள். மணிநேரங்களுக்குப் பதிலாக நிமிடங்களில் அடிப்படைகளை மாஸ்டர் செய்யுங்கள்.',
        lessonDuration: '5-15 நிமிட பாடங்கள்',
        lessonDurationDesc: 'உங்கள் பிஸியான அட்டவணையில் பொருந்தும் குறுகிய, கவனம் செலுத்தும் பாடங்கள்',
        techModules: '22+ தொழில்நுட்ப தொகுதிகள்',
        techModulesDesc: 'AI, இயந்திர கற்றல், வெப் டெவ், சைபர் பாதுகாப்பு மற்றும் பல',
        earnBadges: 'புள்ளிகள் மற்றும் பேட்ஜ்களைப் பெறுங்கள்',
        earnBadgesDesc: 'உங்கள் முன்னேற்றத்தைக் கண்காணித்து உங்கள் சாதனைகளைக் காட்டுங்கள்',
        freeSelfPaced: 'இலவசம் • சுய வேகம் • சான்றிதழ் தயார்',
        readyCareer: 'உங்கள் தொழில் பயணத்தைத் தொடங்க தயாரா?',
        joinThousands: 'இன்று தங்கள் எதிர்காலத்தைப் பாதுகாக்கும் ஆயிரக்கணக்கானோருடன் சேரவும்.',
        goToDashboard: 'டாஷ்போர்டுக்குச் செல்லவும்',
        createProfile: 'இலவச சுயவிவரத்தை உருவாக்கவும்',
        opportunitiesNear: 'உங்களுக்கு அருகில் உள்ள வாய்ப்புகள்',
        studentTitle: 'நான் ஆக விரும்புகிறேன்...',
        student: 'மாணவர்',
        selectInterest: 'ஆர்வப் பகுதியைத் தேர்ந்தெடுக்கவும்',
        interestHint: 'ஆட்டோமோட்டிவ், எலெக்ட்ரானிக்ஸ் போன்ற ஆர்வப் பகுதிகள்.',
        findCourse: 'பாடத்தைக் கண்டறியவும்',
        exploreTitle: 'நான் ஆராய விரும்புகிறேன்...',
        opportunities: 'வாய்ப்புகள்',
        searchJobExchange: 'வேலை பரிமாற்றத்தைத் தேடுங்கள்',
        opportunitiesHint: 'வேலை பரிமாற்றம், பயிற்சி மற்றும் தொழில்முனைவுக்கான வாய்ப்புகள்',
        findJob: 'வேலையைக் கண்டறியவும்',
        notSure: 'உறுதியாக தெரியவில்லை',
        whereBegin: 'எங்கே தொடங்குவது?',
        guidanceSubtitle: 'சில எளிய கேள்விகளுக்கு பதிலளியுங்கள், நாங்கள் உங்களுக்கு உதவுவோம்.',
        educationLevelQuestion: 'உங்கள் உயர்கல்வி நிலை என்ன?',
        selectEducation: 'கல்வியைத் தேர்ந்தெடுக்கவும்',
        next: 'அடுத்து',
        
        // Login & Auth
        welcomeBack: 'மீண்டும் வருக',
        loginSubtitle: 'உங்கள் சரிபார்க்கப்பட்ட சுயவிவரத்தை அணுக உள்நுழைக',
        email: 'மின்னஞ்சல்',
        password: 'கடவுச்சொல்',
        rememberMe: 'என்னை நினைவில் கொள்ளுங்கள்',
        forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
        loginButton: 'உள்நுழைக',
        noAccount: 'கணக்கு இல்லையா?',
        signUp: 'பதிவு செய்க',
        getStarted: 'ஸ்கில்பிரிட்ஜுடன் தொடங்குங்கள்',
        registerNow: 'இப்போதே பதிவு செய்க',
        alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
        name: 'முழு பெயர்',
        phone: 'தொலைபேசி எண்',
        confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
        iAgree: 'நான் ஒப்புக்கொள்கிறேன்',
        termsAndConditions: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
        and: 'மற்றும்',
        privacyPolicy: 'தனியுரிமை கொள்கை',
        
        // Dashboard
        welcome: 'வருக',
        welcomeBack2: 'மீண்டும் வருக',
        dashboard: 'டாஷ்போர்டு',
        careerProgress: 'இன்று உங்கள் தொழில் முன்னேற்றம் இதோ',
        profileCompletion: 'சுயவிவர முடிவு',
        complete: 'முழுமையானது',
        topJobMatches: 'சிறந்த வேலை பொருத்தங்கள்',
        viewAllJobs: 'அனைத்து வேலைகளையும் காண்க',
        myCredentials: 'எனது சான்றுகள்',
        recentActivity: 'சமீபத்திய செயல்பாடு',
        recommendedForYou: 'உங்களுக்கு பரிந்துரைக்கப்பட்டது',
        skillsOverview: 'திறன்கள் மேலோட்டம்',
        viewSkillGap: 'திறன் இடைவெளியைக் காண்க',
        
        // Profile Setup
        profileSetupTitle: 'உங்கள் சுயவிவரத்தை நிறைவு செய்யுங்கள்',
        profileSetupSubtitle: 'தனிப்பயனாக்கப்பட்ட வேலை பொருத்தங்களைப் பெற உங்களைப் பற்றி எங்களிடம் கூறுங்கள்',
        personalInformation: 'தனிப்பட்ட தகவல்',
        contactInformation: 'தொடர்பு தகவல்',
        address: 'முகவரி',
        city: 'நகரம்',
        state: 'மாநிலம்',
        pincode: 'அஞ்சல் குறியீடு',
        education: 'கல்வி',
        highestQualification: 'மிக உயர்ந்த தகுதி',
        fieldOfStudy: 'படிப்புத் துறை',
        institution: 'நிறுவனம்',
        yearOfPassing: 'தேர்ச்சி ஆண்டு',
        skills: 'திறன்கள்',
        addSkills: 'உங்கள் திறன்களைச் சேர்க்கவும்',
        experience: 'அனுபவம்',
        yearsOfExperience: 'அனுபவ ஆண்டுகள்',
        currentCompany: 'தற்போதைய நிறுவனம்',
        jobTitle: 'வேலை தலைப்பு',
        saveChanges: 'மாற்றங்களைச் சேமிக்கவும்',
        cancel: 'ரத்து செய்',
        skip: 'தவிர்க்க',
        skipForNow: 'இப்போதைக்கு தவிர்க்க',
        back: 'பின்',
        continue: 'தொடர்க',
        
        // Resume Upload
        uploadResume: 'விண்ணப்பப் பதிவேற்றம்',
        uploadResumeTitle: 'உங்கள் விண்ணப்பத்தைப் பதிவேற்றவும்',
        uploadResumeSubtitle: 'AI-சக்தி வாய்ந்த திறன் பகுப்பாய்வு மற்றும் தனிப்பயனாக்கப்பட்ட பரிந்துரைகளுக்காக PDF வடிவத்தில் உங்கள் விண்ணப்பத்தைப் பதிவேற்றவும்.',
        chooseFile: 'PDF கோப்பைத் தேர்ந்தெடுக்கவும்',
        dragDropHere: 'அல்லது இங்கே இழுத்து விடுங்கள்',
        maxFileSize: 'அதிகபட்ச கோப்பு அளவு: 5MB',
        changeFile: 'கோப்பை மாற்று',
        resumeUploadedSuccess: 'விண்ணப்பம் வெற்றிகரமாகப் பதிவேற்றப்பட்டது!',
        analyzingResume: 'உங்கள் விண்ணப்பத்தை AI மூலம் பகுப்பாய்வு செய்கிறது...',
        dragDropResume: 'உங்கள் விண்ணப்பத்தை இங்கே இழுத்து விடுங்கள்',
        or: 'அல்லது',
        browseFiles: 'கோப்புகளை உலாவவும்',
        fileRequirements: 'ஆதரிக்கப்படும் வடிவங்கள்: PDF (அதிகபட்சம் 5MB)',
        uploading: 'பதிவேற்றுகிறது',
        analyzing: 'பகுப்பாய்வு செய்கிறது',
        uploadSuccess: 'விண்ணப்பம் வெற்றிகரமாகப் பதிவேற்றப்பட்டது!',
        uploadFailed: 'விண்ணப்பப் பதிவேற்றம் தோல்வியடைந்தது',
        analysisComplete: 'பகுப்பாய்வு முழுமையானது',
        uploadAndAnalyze: 'பதிவேற்று மற்றும் பகுப்பாய்வு செய்',
        uploaded: 'பதிவேற்றப்பட்டது',
        skipForNowBtn: 'இப்போதைக்கு தவிர்க்க',
        whatHappensNext: 'அடுத்து என்ன நடக்கும்?',
        securelyStored: 'உங்கள் விண்ணப்பம் Firebase Storage இல் பாதுகாப்பாக சேமிக்கப்பட்டுள்ளது',
        aiAnalyzes: 'AI உங்கள் திறன்கள், அனுபவம் மற்றும் கல்வியை பகுப்பாய்வு செய்கிறது',
        personalizedRecommendations: 'தனிப்பயனாக்கப்பட்ட வேலை பரிந்துரைகள் மற்றும் திறன் இடைவெளி பகுப்பாய்வைப் பெறுங்கள்',
        encryptedSecure: 'உங்கள் தரவு மறையாக்கப்பட்டு பாதுகாப்பாக சேமிக்கப்பட்டுள்ளது',
        
        // Learning/Micro Learning
        learningTitle: 'மைக்ரோ கற்றல்',
        learningSubtitle: 'சிறிய பாடங்களில் புதிய திறன்களைக் கற்றுக்கொள்ளுங்கள்',
        allCourses: 'அனைத்து பாடநெறிகள்',
        inProgress: 'செயல்பாட்டில்',
        completed: 'முடிந்தது',
        startCourse: 'பாடநெறியைத் தொடங்கு',
        continueLearning: 'கற்றலைத் தொடரவும்',
        lessons: 'பாடங்கள்',
        duration: 'காலம்',
        difficulty: 'சிரமம்',
        beginner: 'தொடக்கநிலை',
        intermediate: 'இடைநிலை',
        advanced: 'மேம்பட்ட',
        enrollNow: 'இப்போது சேரவும்',
        certificateAvailable: 'சான்றிதழ் கிடைக்கிறது',
        
        // Employer Dashboard
        employerPortal: 'முதலாளி போர்ட்டல்',
        employerSubtitle: 'சரிபார்க்கப்பட்ட கிராமப்புற திறமைகளைக் கண்டறிந்து வேலைக்கு அமர்த்துங்கள்',
        postJob: 'வேலை வெளியிடு',
        activeJobs: 'செயல்பாட்டு வேலைகள்',
        totalApplicants: 'மொத்த விண்ணப்பதாரர்கள்',
        interviewed: 'நேர்காணல் செய்யப்பட்டது',
        hired: 'வேலைக்கு அமர்த்தப்பட்டது',
        recentApplicants: 'சமீபத்திய விண்ணப்பதாரர்கள்',
        searchCandidates: 'வேட்பாளர்களைத் தேடுங்கள்',
        viewProfile: 'சுயவிவரத்தைக் காண்க',
        scheduleInterview: 'நேர்காணல் திட்டமிடு',
        shortlist: 'குறுகிய பட்டியல்',
        match: 'பொருத்தம்',
        
        // Common Buttons & Actions
        save: 'சேமிக்கவும்',
        edit: 'திருத்து',
        delete: 'நீக்கு',
        confirm: 'உறுதிப்படுத்து',
        yes: 'ஆம்',
        no: 'இல்லை',
        ok: 'சரி',
        close: 'மூடு',
        submit: 'சமர்ப்பிக்கவும்',
        apply: 'விண்ணப்பிக்கவும்',
        download: 'பதிவிறக்கு',
        share: 'பகிர்',
        viewDetails: 'விவரங்களைக் காண்க',
        viewAll: 'அனைத்தையும் காண்க',
        learnMore: 'மேலும் அறிக',
        search: 'தேடல்',
        loading: 'ஏற்றுகிறது...',
        error: 'பிழை',
        success: 'வெற்றி',
        tryAgain: 'மீண்டும் முயற்சிக்கவும்',
        goBack: 'திரும்பிச் செல்லுங்கள்',
        
        // Messages
        noDataAvailable: 'தரவு இல்லை',
        somethingWentWrong: 'ஏதோ தவறு ஏற்பட்டது',
        pleaseWait: 'தயவுசெய்து காத்திருக்கவும்...',
        processingRequest: 'உங்கள் கோரிக்கையை செயலாக்குகிறது...',
        savedSuccessfully: 'வெற்றிகரமாக சேமிக்கப்பட்டது',
        updatedSuccessfully: 'வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
        deletedSuccessfully: 'வெற்றிகரமாக நீக்கப்பட்டது',
        
        // Skill Gap Dashboard
        skillGapDashboardTitle: 'திறன் இடைவெளி பகுப்பாய்வு டாஷ்போர்டு',
        aiWorkforceInsights: 'AI-சக்தி பணியாளர் திறன் நுண்ணறிவு',
        reseedDemoData: 'டெமோ தரவை மீண்டும் விதைக்கவும்',
        seeding: 'விதைக்கிறது...',
        menu: 'மெனு',
        resumeAnalysis: 'விண்ணப்ப பகுப்பாய்வு',
        analyzed: 'பகுப்பாய்வு செய்யப்பட்டது',
        empty: 'காலி',
        noResumeAnalysisFound: 'விண்ணப்ப பகுப்பாய்வு கிடைக்கவில்லை',
        uploadResumeUnlock: 'AI-சக்தி திறன் நுண்ணறிவு மற்றும் தனிப்பயனாக்கப்பட்ட தொழில் பரிந்துரைகளைத் திறக்க உங்கள் விண்ணப்பத்தைப் பதிவேற்றவும்.',
        resumeScore: 'விண்ணப்ப மதிப்பெண்',
        experienceLevel: 'அனுபவம்',
        detailedAnalysisResults: 'விரிவான பகுப்பாய்வு முடிவுகள்',
        skillMatchingFor: 'திறன் பொருத்தம்',
        selectedRole: 'தேர்ந்தெடுக்கப்பட்ட பங்கு',
        matchPercentage: 'பொருத்த சதவீதம்',
        requiredSkillsPossessed: 'தேவையான திறன்கள் உள்ளன',
        readinessScore: 'தயார்நிலை மதிப்பெண்',
        outOf100: '100 புள்ளிகளில்',
        gapOverview: 'இடைவெளி மேலோட்டம்',
        critical: 'முக்கியமான',
        moderate: 'மிதமான',
        good: 'நன்று',
        skillName: 'திறன் பெயர்',
        required: 'தேவையான',
        user: 'பயனர்',
        status: 'நிலை',
        recommendedLearningAI: 'பரிந்துரைக்கப்பட்ட கற்றல் (AI சக்தி)',
        personalizedTutorials: 'உங்கள் திறன்களின் அடிப்படையில் தனிப்பயனாக்கப்பட்ட டுடோரியல்கள்',
        curatingVideos: 'தனிப்பயனாக்கப்பட்ட வீடியோக்களை தேர்வு செய்கிறது...',
        watchNow: 'இப்போது பார்க்கவும்',
        tutorial: 'டுடோரியல்',
        noVideoRecommendations: 'வீடியோ பரிந்துரைகள் கிடைக்கவில்லை. தனிப்பயனாக்கப்பட்ட கற்றல் பாதைகளைத் திறக்க உங்கள் விண்ணப்பத்தைப் பதிவேற்றவும்.',
        profileOverview: 'சுயவிவர மேலோட்டம்',
        lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
        resumeStatus: 'விண்ணப்ப நிலை',
        verified: 'சரிபார்க்கப்பட்டது',
        pendingUpload: 'பதிவேற்றம் நிலுவையில்',
        skillScore: 'திறன் மதிப்பெண்',
        matchStrength: 'பொருத்த வலிமை',
        quickActions: 'விரைவு செயல்கள்',
        uploadResumeBtn: 'விண்ணப்பத்தைப் பதிவேற்றவும்',
        viewSkillGapReport: 'திறன் இடைவெளி அறிக்கையைக் காண்க',
        exploreCourses: 'பாடநெறிகளை ஆராயுங்கள்',
        tip: 'உதவிக்குறிப்பு',
        completeCriticalSkills: 'உங்கள் பொருத்த வலிமையை 40% வரை அதிகரிக்க உங்கள் சுயவிவரத்தில் முன்னிலைப்படுத்தப்பட்ட முக்கியமான திறன் இடைவெளிகளை நிறைவு செய்யுங்கள்.',
        authenticating: 'அங்கீகரிக்கிறது...',
        loadingDashboard: 'டாஷ்போர்டை ஏற்றுகிறது...',
        
        // Resume Upload Page
        chooseFile: 'PDF கோப்பைத் தேர்ந்தெடுக்கவும்',
        dragDropHere: 'அல்லது இங்கே இழுத்து விடுங்கள்',
        maxFileSize: 'அதிகபட்ச கோப்பு அளவு: 5MB',
        changeFile: 'கோப்பை மாற்றவும்',
        analyzingResume: 'உங்கள் விண்ணப்பத்தை AI மூலம் பகுப்பாய்வு செய்கிறது...',
        resumeUploadedSuccess: 'விண்ணப்பம் வெற்றிகரமாகப் பதிவேற்றப்பட்டது!',
        skipForNowBtn: 'இப்போதைக்கு தவிர்க்க',
        encryptedSecure: 'உங்கள் தரவு குறியாக்கம் செய்யப்பட்டு பாதுகாப்பாக சேமிக்கப்பட்டுள்ளது',
        
        // Profile Setup
        interestedDomain: 'ஆர்வமுள்ள களம்',
        selectDomain: 'உங்கள் விரும்பிய வேலை பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
        selectSkills: 'உங்கள் திறன்களைத் தேர்ந்தெடுக்கவும்',
        selectSkillsHint: 'நீங்கள் வைத்திருக்கும் அல்லது கற்க விரும்பும் திறன்களைத் தேர்வுசெய்க',
        fieldOfInterest: 'ஆர்வத் துறை',
        enterFieldInterest: 'உங்கள் குறிப்பிட்ட ஆர்வத் துறையை உள்ளிடவும்',
        experienceLevelLabel: 'அனுபவ நிலை',
        selectExperienceLevel: 'உங்கள் அனுபவ நிலையைத் தேர்ந்தெடுக்கவும்',
        locationLabel: 'விருப்பமான இடம்',
        selectLocation: 'விருப்பமான பணி இடத்தைத் தேர்ந்தெடுக்கவும்',
        fresher: 'புதியவர்',
        junior: 'ஜூனியர்',
        midLevel: 'நடுநிலை',
        senior: 'மூத்த',
        
        // Basic Info
        fullName: 'முழு பெயர்',
        phoneNumber: 'தொலைபேசி எண்',
        dateOfBirth: 'பிறந்த தேதி',
        gender: 'பாலினம்',
        male: 'ஆண்',
        female: 'பெண்',
        other: 'மற்றவை',
        district: 'மாவட்டம்',
        selectDistrict: 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
        selectState: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
        selectGender: 'பாலினத்தைத் தேர்ந்தெடுக்கவும்',
        basicInfoTitle: 'அடிப்படை தகவல்',
        basicInfoSubtitle: 'உங்கள் தனிப்பட்ட விவரங்களை வழங்கவும்',
        
        // Validation Messages
        nameRequired: 'முழு பெயர் தேவை',
        nameMinLength: 'பெயர் குறைந்தது 3 எழுத்துகள் இருக்க வேண்டும்',
        phoneRequired: 'தொலைபேசி எண் தேவை',
        invalidPhone: 'சரியான 10 இலக்க இந்திய மொபைல் எண்ணை உள்ளிடவும்',
        invalidEmail: 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
        dobRequired: 'பிறந்த தேதி தேவை',
        ageRestriction: 'வயது 18 மற்றும் 100 ஆண்டுகளுக்கு இடையில் இருக்க வேண்டும்',
        genderRequired: 'உங்கள் பாலினத்தைத் தேர்ந்தெடுக்கவும்',
        stateRequired: 'உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
        districtRequired: 'மாவட்டம் தேவை',
        domainRequired: 'உங்கள் ஆர்வமுள்ள களத்தைத் தேர்ந்தெடுக்கவும்',
        skillsRequired: 'குறைந்தது ஒரு திறனையாவது தேர்ந்தெடுக்கவும்',
        fieldRequired: 'உங்கள் ஆர்வத் துறையை உள்ளிடவும்'
    },
    ml: {
        // Navbar
        findJobs: 'ജോലികൾ കണ്ടെത്തുക',
        internships: 'ഇന്റേൺഷിപ്പുകൾ',
        skillGap: 'കഴിവ് വിടവ്',
        forEmployers: 'തൊഴിലധാതാക്കൾക്ക്',
        kioskMode: 'കിയോസ്ക് മോഡ്',
        startLearning: 'പഠനം ആരംഭിക്കുक',
        logout: 'പുറത്തുകടക്കുക',
        login: 'ലോഗിൻ ചെയ്യുക',
        register: 'രജിസ്റ്റർ ചെയ്യുക',
        
        // Jobs
        jobsTitle: 'നിങ്ങളുടെ തികഞ്ഞ ജോലി കണ്ടെത്തുക',
        jobsDescription: 'നിങ്ങളുടെ സാക്ഷ്യപ്പെടുത്തിയ പ്രൊഫൈലിനെ അടിസ്ഥാനമാക്കിയുള്ള AI-പൊരുത്തം അവസരങ്ങൾ.',
        searchJobs: 'തലക്കെട്ട്, കഴിവ്, അല്ലെങ്കിൽ കമ്പനി വഴി ജോലികൾ തിരയുക...',
        uploadResumePrompt: 'വ്യക്തിഗത പൊരുത്ത സ്കോറുകൾ കാണാൻ റെസ്യൂം അപ്ലോഡ് ചെയ്യുക',
        uploadNow: 'ഇപ്പോൾ അപ്ലോഡ് ചെയ്യുക',
        noJobsFound: 'നിങ്ങളുടെ തെറ്റലുമായി പൊരുത്തുന്ന ജോലികൾ കണ്ടെത്തിയില്ല',
        whyMatch: 'നിങ്ങൾ എന്തുകൊണ്ട് പൊരുത്തുന്നു:',
        missing: 'നഷ്ടപ്പെട്ടത്',
        uploadForMatch: 'പൊരുത്തത്തിന് അപ്ലോഡ് ചെയ്യുക',
        trustedEmployer: 'വിശ്വസനീയ തൊഴിലധാതാവ്',
        applyNow: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
        details: 'വിശദാംശങ്ങൾ',
        
        // Internships
        internshipsTitle: 'നിങ്ങളുടെ സ്വപ്ന ഇന്റേൺഷിപ്പ് കണ്ടെത്തുക',
        internshipsDescription: 'യഥാർത്ഥ വിശ്വ അനുഭവം നേടുകയും കരിയർ ആരംഭിക്കുകയും ചെയ്യുക',
        domain: 'ഡൊമൈന്',
        allDomains: 'എല്ലാ ഡൊമൈനുകളും',
        location: 'സ്ഥലം',
        allLocations: 'എല്ലാ സ്ഥലങ്ങളും',
        internshipType: 'ഇന്റർൻഷിപ് തരം',
        allTypes: 'എല്ലാ തരങ്ങളും',
        paid: 'പൈഡ്',
        unpaid: 'പൈഡ് അല്ല',
        stipend: 'സ്റ്റൈപ്പന്റ്',
        applicants: 'അപേക്ഷകർ',
        posted: 'പോസ്റ്റ് ചെയ്തത്',
        noInternshipsFound: 'ഇന്റർൻഷിപ്പുകൾ കണ്ടെത്തിയില്ല',
        adjustFilters: 'കൂടുതൽ ഫലങ്ങൾ കാണാൻ നിങ്ങളുടെ ഫിലട്ടറുകൾ അഡ്ജസ്റ്റ് ചെയ്യുക',
        applyFilters: 'ഫിലട്ടറുകൾ പ്രയോഗിക്കുക',
        
        // Common
        filters: 'ഫിൽട്ടറുകൾ',
        clearFilters: 'ഫി ൽട്ടറുകൾ ക്ലീയർ ചെയ്യുക',
        resetFilters: 'ഫിൽട്ടറുകൾ റീസെറ്റ് ചെയ്യുക',
        salary: 'ശമ്പളം',
        minimumSalary: 'കുറഞ്ഞ ശമ്പളം',
        company: 'കമ്പനി',
        type: 'തരം',
        jobType: 'ജോലി തരം',
        fullTime: 'മുഴുവൻ സമയം',
        partTime: 'പാർട്ട് ടൈം',
        contract: 'കോൺട്രാക്ട്',
        gig: 'ഗിഗ്',
        remote: 'റിമോട്ട്',
        onsite: 'ഓൺസൈറ്റ്',
        hybrid: 'ഹൈബ്രിഡ്',
        
        // Landing Page
        heroTagline: 'പ്രതിഭയെ അവസരത്തുമായി പൊരുത്തിപ്പിക്കുന്നു',
        heroTitle1: 'ജോലി നേടുക. സാക്ഷ്യപ്പെടുത്തുക.',
        heroTitle2: 'മുന്നേറുക.',
        heroSubtitle: 'ഗ്രാമീണ പ്രതിഭകള്‍ക്കുള്ള ഇന്ത്യയുടെ മുതല് ബ്ലോക്‌ചെയിൻ-സാക്ഷ്യപ്പെടുത്തിയ തൊഴില്‍ പ്ലാറ്റ്‌ഫോം. പ്രമുഖ തൊഴില്‍ദാതാക്കളുമായി പൊരുത്തുകയും നിങ്ങളുടെ കഴിവുകള്‍ ഉടന് തന്നെ തന്നെ തെളിയിക്കുകയും ചെയ്യുക.',
        jobSeeker: 'ഞാൻ ജോലി അന്വേഷിക്കുന്നു',
        startLearningNow: 'ഇപ്പോൾ പഠനം ആരംഭിക്കുക',
        governmentVerified: 'സർക്കാർ സാക്ഷ്യപ്പെടുത്തിയത്',
        candidates10L: '10L+ ഉമ്മീദ്വാരൻമാർ',
        youthUnaware: 'പൊരുത്തുന്ന ജോലികൾ കുറിച്ച് അറിയാത്ത യുവാക്കൾ',
        verifiedProfiles: 'സാക്ഷ്യപ്പെടുത്തിയ പ്രൊഫൈലുകൾ',
        corporatePartners: 'കോർപ്പറേറ്റ് പാർട്ട്നർമാർ',
        whyChoose: 'എന്തുകൊണ്ട് SkillBridge തെരഞ്ഞെടുക്കണം?',
        bridgingGap: 'പ്രതിഭയും അവസരവും തമ്മിലുള്ള വിടവ് മേടുന്നു.',
        verifiedCredentialsTitle: 'സാക്ഷ്യപ്പെടുത്തിയ സാക്ഷ്യപത്രങ്ങൾ',
        verifiedCredentialsDesc: 'നിങ്ങളുടെ കഴിവുകളും വിദ്യാഭ്യാസവും ബ്ലോക്‌ചെയിൻല്‍ സാക്ഷ്യപ്പെടുത്തിയതാണ്. വ്യാജര്‍‍സ്‌യൂമുകൾ ഇല്ല.',
        skillGapAnalysisTitle: 'കഴിവ് വിടവ് പരിശോധന',
        skillGapAnalysisDesc: 'നിങ്ങളുടെ സ്വപ്ന ജോലി നേടാന്‍ എന്ത് കഴിവുകളാണ് ആവശ്യമെന്ന് AI മൂല്യമാപനത്തിലൂടെ കണ്ടുപിടിക്കുക.',
        instantMatchingTitle: 'ഉടനടി പൊരുത്തം',
        instantMatchingDesc: 'കന്നേൺ്റെ എഐ നിങ്ങളുടെ പ്രൊഫൈലുമായി നന്നായി പൊരുത്തുന്ന ജോലികളുമായി പൊരുത്തുന്നു. ഒരു ക്ലിക്കിൽ അപേക്ഷിക്കുക.',
        microLearningTitle: 'മൈക്രോ പഠനത്തിലൂടെ കഴിവുകൾ മാസ്റ്റർ ചെയ്യുക',
        microLearningSubtitle: 'ചെറിയ പാഠങ്ങളിൽ പുതിയ കഴിവുകൾ പതിക്കുക. മണിക്കൂറുകളുക്കു ബദലായി നിമിഷങ്ങളിൽ അടിസ്ഥാനങ്ങൾ മാസ്റ്റർ ചെയ്യുക.',
        lessonDuration: '5-15 മിനിറ്റ് പാഠങ്ങൾ',
        lessonDurationDesc: 'നിങ്ങളുടെ തിരക്കുള്ള ഷെഡ്യൂളില്‍ പൊരുത്തുന്ന ചുരുക്കിയ, ശ്രദ്ധ കേന്ദ്രീകരിച്ച പാഠങ്ങൾ',
        techModules: '22+ സാങ്കേതിക മോഡ്യൂളുകൾ',
        techModulesDesc: 'AI, മെഷീൻ ലെർണ്ണിംഗ്, വെബ്‌ ഡെവ്, സൈബർ സെക്യൂരിറ്റി മറ്റും',
        earnBadges: 'പോയിന്റുകളും ബാഡ്‌ജുകളും നേടുക',
        earnBadgesDesc: 'നിങ്ങളുടെ പ്രഗതി ട്രാക്ക് ചെയ്യുകയും നേട്ടങ്ങൾ പ്രദർ‍ശിപ്പിക്കുകയും ചെയ്യുക',
        freeSelfPaced: 'സൗജന്യം • സ്വയം വേഗത • സർട്ടിഫിക്കറ്റ് തയ്യാര്',
        readyCareer: 'നിങ്ങളുടെ തൊഴില്‍ യാത്ര ആരംഭിക്കാന്‍ തയ്യാരോ?',
        joinThousands: 'ഇന്ന് തങ്ങളുടെ ഭവിഷ്യത്ത് സുരക്ഷിതമാക്കുന്ന ആയിരങ്ങളോടു ചേരുക.',
        goToDashboard: 'ഡാഷ്‍ബോർഡിലേക്ക് പോകുക',
        createProfile: 'സൗജന്യ പ്രൊഫൈല്‍ നിർമ്മിക്കുക',
        opportunitiesNear: 'നിങ്ങളുടെ അരുകിലുള്ള അവസരങ്ങൾ',
        studentTitle: 'ഞാൻ ആകാൻ ആഗ്രഹിക്കുന്നു...',
        student: 'വിദ്യാർത്ഥി',
        selectInterest: 'ആസക്തി മേഖല തെരഞ്ഞെടുക്കുക',
        interestHint: 'ഓട്ടോമോട്ടീവ്, ഇലക്ട്രോണിക്സ് പോലുള്ള ആസക്തി മേഖലകൾ.',
        findCourse: 'കോർസ് കണ്ടെത്തുക',
        exploreTitle: 'ഞാൻ പരിശോധിക്കാൻ ആഗ്രഹിക്കുന്നു...',
        opportunities: 'അവസരങ്ങൾ',
        searchJobExchange: 'ജോലി എക്സ്‌ചെയിഞ്ച്‌ തിരയുക',
        opportunitiesHint: 'ജോലി എക്സ്‌ചെയിഞ്ച്, അപ്രെന്റിസ്ഷിപ്പ്, കരിയർ തുടങ്ങുന്നതിനുള്ള അവസരങ്ങൾ',
        findJob: 'ജോലി കണ്ടെത്തുക',
        notSure: 'ഉറപ്പില്ല',
        whereBegin: 'എവിടദിരുന്ന് ആരംഭിക്കണം?',
        guidanceSubtitle: 'ചില സഹജമായ ചോദ്യങ്ങള്‍ക്ക് ഉത്തരമളിക്കുക, ഞങ്ങൾ നിങ്ങളെ സഹായിക്കും.',
        educationLevelQuestion: 'നിങ്ങളുടെ ഉച്ച വിദ്യാഭ്യാസ തലമെന്താണ്?',
        selectEducation: 'വിദ്യാഭ്യാസം തെരഞ്ഞെടുക്കുക',
        next: 'അടുത്തത്',
        
        // Login & Auth
        welcomeBack: 'തിരികെ സ്വാഗതം',
        loginSubtitle: 'നിങ്ങളുടെ പരിശോധിച്ച പ്രൊഫൈൽ ആക്സസ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക',
        email: 'ഇമെയിൽ',
        password: 'പാസ്‌വേഡ്',
        rememberMe: 'എന്നെ ഓർക്കുക',
        forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
        loginButton: 'ലോഗിൻ',
        noAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
        signUp: 'സൈൻ അപ്പ് ചെയ്യുക',
        getStarted: 'സ്കിൽബ്രിഡ്ജിൽ ആരംഭിക്കുക',
        registerNow: 'ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക',
        alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
        name: 'പൂർണ്ണ പേര്',
        phone: 'ഫോൺ നമ്പർ',
        confirmPassword: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
        iAgree: 'ഞാൻ സമ്മതിക്കുന്നു',
        termsAndConditions: 'നിബന്ധനകളും വ്യവസ്ഥകളും',
        and: 'ഒപ്പം',
        privacyPolicy: 'സ്വകാര്യതാ നയം',
        
        // Dashboard
        welcome: 'സ്വാഗതം',
        welcomeBack2: 'തിരികെ സ്വാഗതം',
        dashboard: 'ഡാഷ്‌ബോർഡ്',
        careerProgress: 'ഇന്ന് നിങ്ങളുടെ കരിയർ പുരോഗതി ഇതാ',
        profileCompletion: 'പ്രൊഫൈൽ പൂർത്തീകരണം',
        complete: 'പൂർണ്ണം',
        topJobMatches: 'മികച്ച ജോലി പൊരുത്തങ്ങൾ',
        viewAllJobs: 'എല്ലാ ജോലികളും കാണുക',
        myCredentials: 'എന്റെ ക്രെഡൻഷ്യലുകൾ',
        recentActivity: 'സമീപകാല പ്രവർത്തനം',
        recommendedForYou: 'നിങ്ങൾക്കായി ശുപാർശ ചെയ്യുന്നു',
        skillsOverview: 'കഴിവുകളുടെ അവലോകനം',
        viewSkillGap: 'സ്കിൽ വിടവ് കാണുക',
        
        // Profile Setup
        profileSetupTitle: 'നിങ്ങളുടെ പ്രൊഫൈൽ പൂർത്തിയാക്കുക',
        profileSetupSubtitle: 'വ്യക്തിഗതമാക്കിയ ജോലി പൊരുത്തങ്ങൾ ലഭിക്കാൻ നിങ്ങളെക്കുറിച്ച് ഞങ്ങളോട് പറയുക',
        personalInformation: 'വ്യക്തിഗത വിവരങ്ങൾ',
        contactInformation: 'ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ',
        address: 'വിലാസം',
        city: 'നഗരം',
        state: 'സംസ്ഥാനം',
        pincode: 'പിൻകോഡ്',
        education: 'വിദ്യാഭ്യാസം',
        highestQualification: 'ഏറ്റവും ഉയർന്ന യോഗ്യത',
        fieldOfStudy: 'പഠന മേഖല',
        institution: 'സ്ഥാപനം',
        yearOfPassing: 'വിജയ വർഷം',
        skills: 'കഴിവുകൾ',
        addSkills: 'നിങ്ങളുടെ കഴിവുകൾ ചേർക്കുക',
        experience: 'അനുഭവം',
        yearsOfExperience: 'അനുഭവ വർഷങ്ങൾ',
        currentCompany: 'നിലവിലെ കമ്പനി',
        jobTitle: 'ജോലി തലക്കെട്ട്',
        saveChanges: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
        cancel: 'റദ്ദാക്കുക',
        skip: 'ഒഴിവാക്കുക',
        skipForNow: 'ഇപ്പോൾ ഒഴിവാക്കുക',
        back: 'തിരികെ',
        continue: 'തുടരുക',
        
        // Resume Upload
        uploadResume: 'റെസ്യൂം അപ്‌ലോഡ്',
        uploadResumeTitle: 'നിങ്ങളുടെ റെസ്യൂം അപ്‌ലോഡ് ചെയ്യുക',
        uploadResumeSubtitle: 'AI-പവർഡ് സ്കിൽ അനാലിസിസിനും വ്യക്തിഗതമാക്കിയ ശുപാർശകൾക്കുമായി PDF ഫോർമാറ്റിൽ നിങ്ങളുടെ റെസ്യൂം അപ്‌ലോഡ് ചെയ്യുക.',
        chooseFile: 'PDF ഫയൽ തിരഞ്ഞെടുക്കുക',
        dragDropHere: 'അല്ലെങ്കിൽ ഇവിടെ വലിച്ചിട്ടിടുക',
        maxFileSize: 'പരമാവധി ഫയൽ വലുപ്പം: 5MB',
        changeFile: 'ഫയൽ മാറ്റുക',
        resumeUploadedSuccess: 'റെസ്യൂം വിജയകരമായി അപ്‌ലോഡ് ചെയ്തു!',
        analyzingResume: 'നിങ്ങളുടെ റെസ്യൂം AI ഉപയോഗിച്ച് വിശകലനം ചെയ്യുന്നു...',
        dragDropResume: 'നിങ്ങളുടെ റെസ്യൂം ഇവിടെ വലിച്ചിട്ടിടുക',
        or: 'അല്ലെങ്കിൽ',
        browseFiles: 'ഫയലുകൾ ബ്രൗസ് ചെയ്യുക',
        fileRequirements: 'പിന്തുണയ്ക്കുന്ന ഫോർമാറ്റുകൾ: PDF (പരമാവധി 5MB)',
        uploading: 'അപ്‌ലോഡ് ചെയ്യുന്നു',
        analyzing: 'വിശകലനം ചെയ്യുന്നു',
        uploadSuccess: 'റെസ്യൂം വിജയകരമായി അപ്‌ലോഡ് ചെയ്തു!',
        uploadFailed: 'റെസ്യൂം അപ്‌ലോഡ് പരാജയപ്പെട്ടു',
        analysisComplete: 'വിശകലനം പൂർത്തിയായി',
        uploadAndAnalyze: 'അപ്‌ലോഡ് ചെയ്ത് വിശകലനം നടത്തുക',
        uploaded: 'അപ്‌ലോഡ് ചെയ്തു',
        skipForNowBtn: 'ഇപ്പോൾ ഒഴിവാക്കുക',
        whatHappensNext: 'അടുത്തതായി എന്താണ് സംഭവിക്കുന്നത്?',
        securelyStored: 'നിങ്ങളുടെ റെസ്യൂം Firebase Storage-ൽ സുരക്ഷിതമായി സംഭരിച്ചു',
        aiAnalyzes: 'AI നിങ്ങളുടെ കഴിവുകൾ, അനുഭവം, വിദ്യാഭ്യാസം എന്നിവ വിശകലനം ചെയ്യുന്നു',
        personalizedRecommendations: 'വ്യക്തിഗതമാക്കിയ ജോലി ശുപാർശകളും സ്കിൽ ഗ്യാപ് അനാലിസിസും നേടുക',
        encryptedSecure: 'നിങ്ങളുടെ ഡാറ്റ എൻക്രിപ്റ്റ് ചെയ്തതും സുരക്ഷിതമായി സംഭരിച്ചതുമാണ്',
        
        // Learning/Micro Learning
        learningTitle: 'മൈക്രോ ലേണിംഗ്',
        learningSubtitle: 'ചെറിയ പാഠങ്ങളിൽ പുതിയ കഴിവുകൾ പഠിക്കുക',
        allCourses: 'എല്ലാ കോഴ്‌സുകളും',
        inProgress: 'പുരോഗതിയിൽ',
        completed: 'പൂർത്തിയായി',
        startCourse: 'കോഴ്‌സ് ആരംഭിക്കുക',
        continueLearning: 'പഠനം തുടരുക',
        lessons: 'പാഠങ്ങൾ',
        duration: 'കാലയളവ്',
        difficulty: 'ബുദ്ധിമുട്ട്',
        beginner: 'തുടക്കക്കാരൻ',
        intermediate: 'ഇടത്തരം',
        advanced: 'അഡ്വാൻസ്ഡ്',
        enrollNow: 'ഇപ്പോൾ എൻറോൾ ചെയ്യുക',
        certificateAvailable: 'സർട്ടിഫിക്കറ്റ് ലഭ്യമാണ്',
        
        // Employer Dashboard
        employerPortal: 'തൊഴിലുടമ പോർട്ടൽ',
        employerSubtitle: 'പരിശോധിച്ച ഗ്രാമീണ പ്രതിഭകളെ കണ്ടെത്തി നിയമിക്കുക',
        postJob: 'ജോലി പോസ്റ്റ് ചെയ്യുക',
        activeJobs: 'സജീവ ജോലികൾ',
        totalApplicants: 'മൊത്തം അപേക്ഷകർ',
        interviewed: 'അഭിമുഖം നടത്തി',
        hired: 'നിയമിച്ചു',
        recentApplicants: 'സമീപകാല അപേക്ഷകർ',
        searchCandidates: 'കാൻഡിഡേറ്റുകളെ തിരയുക',
        viewProfile: 'പ്രൊഫൈൽ കാണുക',
        scheduleInterview: 'അഭിമുഖം ഷെഡ്യൂൾ ചെയ്യുക',
        shortlist: 'ഷോർട്ട്ലിസ്റ്റ്',
        match: 'പൊരുത്തം',
        
        // Common Buttons & Actions
        save: 'സംരക്ഷിക്കുക',
        edit: 'എഡിറ്റ്',
        delete: 'ഇല്ലാതാക്കുക',
        confirm: 'സ്ഥിരീകരിക്കുക',
        yes: 'അതെ',
        no: 'ഇല്ല',
        ok: 'ശരി',
        close: 'അടയ്ക്കുക',
        submit: 'സമർപ്പിക്കുക',
        apply: 'അപേക്ഷിക്കുക',
        download: 'ഡൗൺലോഡ്',
        share: 'പങ്കിടുക',
        viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
        viewAll: 'എല്ലാം കാണുക',
        learnMore: 'കൂടുതൽ അറിയുക',
        search: 'തിരയുക',
        loading: 'ലോഡുചെയ്യുന്നു...',
        error: 'പിശക്',
        success: 'വിജയം',
        tryAgain: 'വീണ്ടും ശ്രമിക്കുക',
        goBack: 'തിരികെ പോകുക',
        
        // Messages
        noDataAvailable: 'ഡാറ്റ ലഭ്യമല്ല',
        somethingWentWrong: 'എന്തോ തെറ്റ് സംഭവിച്ചു',
        pleaseWait: 'ദയവായി കാത്തിരിക്കുക...',
        processingRequest: 'നിങ്ങളുടെ അഭ്യർത്ഥന പ്രോസസ് ചെയ്യുന്നു...',
        savedSuccessfully: 'വിജയകരമായി സംരക്ഷിച്ചു',
        updatedSuccessfully: 'വിജയകരമായി അപ്ഡേറ്റ് ചെയ്തു',
        deletedSuccessfully: 'വിജയകരമായി ഇല്ല താക്കി',
        
        // Skill Gap Dashboard
        skillGapDashboardTitle: 'സ്കിൽ വിടവ് വിശകലന ഡാഷ്‌ബോർഡ്',
        aiWorkforceInsights: 'AI-പവർഡ് തൊഴിൽശക്തി കഴിവ് ഉൾക്കാഴ്ചകൾ',
        reseedDemoData: 'ഡെമോ ഡാറ്റ പുനഃസജ്ജമാക്കുക',
        seeding: 'വിതയ്ക്കുന്നു...',
        menu: 'മെനു',
        resumeAnalysis: 'റെസ്യൂം വിശകലനം',
        analyzed: 'വിശകലനം ചെയ്തു',
        empty: 'ശൂന്യം',
        noResumeAnalysisFound: 'റെസ്യൂം വിശകലനം കണ്ടെത്തിയില്ല',
        uploadResumeUnlock: 'AI-പവർഡ് സ്കിൽ ഇൻസൈറ്റുകളും വ്യക്തിഗത കരിയർ ശുപാർശകളും അൺലോക്ക് ചെയ്യാൻ നിങ്ങളുടെ റെസ്യൂം അപ്‌ലോഡ് ചെയ്യുക.',
        resumeScore: 'റെസ്യൂം സ്കോർ',
        experienceLevel: 'പരിചയം',
        detailedAnalysisResults: 'വിശദമായ വിശകലന ഫലങ്ങൾ',
        skillMatchingFor: 'സ്കിൽ പൊരുത്തം',
        selectedRole: 'തിരഞ്ഞെടുത്ത റോൾ',
        matchPercentage: 'പൊരുത്ത ശതമാനം',
        requiredSkillsPossessed: 'ആവശ്യമായ കഴിവുകൾ ഉണ്ട്',
        readinessScore: 'റെഡിനസ് സ്കോർ',
        outOf100: '100 പോയിന്റിൽ',
        gapOverview: 'വിടവ് അവലോകനം',
        critical: 'നിർണായകം',
        moderate: 'മധ്യമം',
        good: 'നല്ലത്',
        skillName: 'കഴിവിന്റെ പേര്',
        required: 'ആവശ്യമുള്ളത്',
        user: 'ഉപയോക്താവ്',
        status: 'നില',
        recommendedLearningAI: 'ശുപാർശ ചെയ്ത പഠനം (AI പവർഡ്)',
        personalizedTutorials: 'നിങ്ങളുടെ കഴിവുകളെ അടിസ്ഥാനമാക്കിയുള്ള വ്യക്തിഗത ട്യൂട്ടോറിയലുകൾ',
        curatingVideos: 'വ്യക്തിഗത വീഡിയോകൾ ക്യൂറേറ്റ് ചെയ്യുന്നു...',
        watchNow: 'ഇപ്പോൾ കാണുക',
        tutorial: 'ട്യൂട്ടോറിയൽ',
        noVideoRecommendations: 'വീഡിയോ ശുപാർശകൾ കണ്ടെത്തിയില്ല. വ്യക്തിഗത പഠന പാതകൾ അൺലോക്ക് ചെയ്യാൻ നിങ്ങളുടെ റെസ്യൂം അപ്‌ലോഡ് ചെയ്യുക.',
        profileOverview: 'പ്രൊഫൈൽ അവലോകനം',
        lastUpdated: 'അവസാനം അപ്‌ഡേറ്റ് ചെയ്തത്',
        resumeStatus: 'റെസ്യൂം നില',
        verified: 'സ്ഥിരീകരിച്ചു',
        pendingUpload: 'അപ്‌ലോഡ് തീർപ്പാക്കാത്തത്',
        skillScore: 'സ്കിൽ സ്കോർ',
        matchStrength: 'പൊരുത്ത ശക്തി',
        quickActions: 'പെട്ടെന്നുള്ള പ്രവർത്തനങ്ങൾ',
        uploadResumeBtn: 'റെസ്യൂം അപ്‌ലോഡ് ചെയ്യുക',
        viewSkillGapReport: 'സ്കിൽ വിടവ് റിപ്പോർട്ട് കാണുക',
        exploreCourses: 'കോഴ്‌സുകൾ പര്യവേക്ഷണം ചെയ്യുക',
        tip: 'നുറുങ്ങ്',
        completeCriticalSkills: 'നിങ്ങളുടെ പൊരുത്ത ശക്തി 40% വരെ വർദ്ധിപ്പിക്കാൻ നിങ്ങളുടെ പ്രൊഫൈലിൽ എടുത്തുകാണിച്ച നിർണായക സ്കിൽ വിടവുകൾ പൂർത്തിയാക്കുക.',
        authenticating: 'ആധികാരികത സ്ഥാപിക്കുന്നു...',
        loadingDashboard: 'ഡാഷ്‌ബോർഡ് ലോഡ് ചെയ്യുന്നു...',
        
        // Resume Upload Page
        chooseFile: 'PDF ഫയൽ തിരഞ്ഞെടുക്കുക',
        dragDropHere: 'അല്ലെങ്കിൽ ഇവിടെ ഡ്രാഗ് ചെയ്ത് ഡ്രോപ്പ് ചെയ്യുക',
        maxFileSize: 'പരമാവധി ഫയൽ വലുപ്പം: 5MB',
        changeFile: 'ഫയൽ മാറ്റുക',
        analyzingResume: 'നിങ്ങളുടെ റെസ്യൂം AI ഉപയോഗിച്ച് വിശകലനം ചെയ്യുന്നു...',
        resumeUploadedSuccess: 'റെസ്യൂം വിജയകരമായി അപ്‌ലോഡ് ചെയ്തു!',
        skipForNowBtn: 'ഇപ്പോൾ ഒഴിവാക്കുക',
        encryptedSecure: 'നിങ്ങളുടെ ഡാറ്റ എൻക്രിപ്റ്റ് ചെയ്‌ത് സുരക്ഷിതമായി സൂക്ഷിച്ചിരിക്കുന്നു',
        
        // Profile Setup
        interestedDomain: 'താൽപര്യമുള്ള ഡൊമെയ്ൻ',
        selectDomain: 'നിങ്ങളുടെ ആവശ്യമുള്ള ജോലി റോൾ തിരഞ്ഞെടുക്കുക',
        selectSkills: 'നിങ്ങളുടെ കഴിവുകൾ തിരഞ്ഞെടുക്കുക',
        selectSkillsHint: 'നിങ്ങൾക്കുള്ള അല്ലെങ്കിൽ പഠിക്കാൻ ആഗ്രഹിക്കുന്ന കഴിവുകൾ തിരഞ്ഞെടുക്കുക',
        fieldOfInterest: 'താൽപര്യമുള്ള മേഖല',
        enterFieldInterest: 'നിങ്ങളുടെ പ്രത്യേക താൽപര്യ മേഖല നൽകുക',
        experienceLevelLabel: 'അനുഭവ തലം',
        selectExperienceLevel: 'നിങ്ങളുടെ അനുഭവ തലം തിരഞ്ഞെടുക്കുക',
        locationLabel: 'ഇഷ്ടപ്പെട്ട സ്ഥലം',
        selectLocation: 'ഇഷ്ടപ്പെട്ട തൊഴിൽ സ്ഥലം തിരഞ്ഞെടുക്കുക',
        fresher: 'പുതുമുഖം',
        junior: 'ജൂനിയർ',
        midLevel: 'മിഡ്-ലെവൽ',
        senior: 'സീനിയർ',
        
        // Basic Info
        fullName: 'മുഴുവൻ പേര്',
        phoneNumber: 'ഫോൺ നമ്പർ',
        dateOfBirth: 'ജനനത്തീയതി',
        gender: 'ലിംഗം',
        male: 'പുരുഷൻ',
        female: 'സ്ത്രീ',
        other: 'മറ്റുള്ളവ',
        district: 'ജില്ല',
        selectDistrict: 'ജില്ല തിരഞ്ഞെടുക്കുക',
        selectState: 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
        selectGender: 'ലിംഗം തിരഞ്ഞെടുക്കുക',
        basicInfoTitle: 'അടിസ്ഥാന വിവരങ്ങൾ',
        basicInfoSubtitle: 'നിങ്ങളുടെ വ്യക്തിഗത വിശദാംശങ്ങൾ നൽകുക',
        
        // Validation Messages
        nameRequired: 'മുഴുവൻ പേര് ആവശ്യമാണ്',
        nameMinLength: 'പേര് കുറഞ്ഞത് 3 അക്ഷരങ്ങൾ ആയിരിക്കണം',
        phoneRequired: 'ഫോൺ നമ്പർ ആവശ്യമാണ്',
        invalidPhone: 'സാധുവായ 10 അക്ക ഇന്ത്യൻ മൊബൈൽ നമ്പർ നൽകുക',
        invalidEmail: 'സാധുവായ ഇമെയിൽ വിലാസം നൽകുക',
        dobRequired: 'ജനനത്തീയതി ആവശ്യമാണ്',
        ageRestriction: 'പ്രായം 18 നും 100 നും ഇടയിലായിരിക്കണം',
        genderRequired: 'ദയവായി നിങ്ങളുടെ ലിംഗം തിരഞ്ഞെടുക്കുക',
        stateRequired: 'ദയവായി നിങ്ങളുടെ സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
        districtRequired: 'ജില്ല ആവശ്യമാണ്',
        domainRequired: 'നിങ്ങളുടെ താൽപര്യം ഡൊമെയ്ൻ തിരഞ്ഞെടുക്കുക',
        skillsRequired: 'കുറഞ്ഞത് ഒരു കഴിവെങ്കിലും തിരഞ്ഞെടുക്കുക',
        fieldRequired: 'നിങ്ങളുടെ താൽപര്യ മേഖല നൽകുക'
    },
    hi: {
        // Navbar
        findJobs: 'नौकरियां खोजें',
        internships: 'इंटर्नशिप',
        skillGap: 'कौशल अंतर',
        forEmployers: 'नियोक्ताओं के लिए',
        kioskMode: 'कियोस्क मोड',
        startLearning: 'सीखना शुरू करें',
        logout: 'लॉग आउट',
        login: 'लॉग इन',
        register: 'रजिस्टर करें',
        
        // Jobs
        jobsTitle: 'अपनी परफेक्ट नौकरी खोजें',
        jobsDescription: 'आपकी सत्यापित प्रोफ़ाइल के आधार पर AI-मिलान अवसर।',
        searchJobs: 'शीर्षक, कौशल या कंपनी द्वारा खोजें...',
        uploadResumePrompt: 'व्यक्तिगत मैच स्कोर देखने के लिए रिज्यूमे अपलोड करें',
        uploadNow: 'अभी अपलोड करें',
        noJobsFound: 'आपकी खोज से मेल खाती कोई नौकरियां नहीं मिलीं',
        whyMatch: 'आप क्यों मेल खाते हैं:',
        missing: 'गुम',
        uploadForMatch: 'मैच के लिए अपलोड करें',
        trustedEmployer: 'विश्वसनीय नियोक्ता',
        applyNow: 'अभी आवेदन करें',
        details: 'विवरण',
        
        // Internships
        internshipsTitle: 'अपनी ड्रीम इंटर्नशिप खोजें',
        internshipsDescription: 'वास्तविक दुनिया का अनुभव प्राप्त करें और अपना करियर शुरू करें',
        domain: 'डोमेन',
        allDomains: 'सभी डोमेन',
        location: 'स्थान',
        allLocations: 'सभी स्थान',
        internshipType: 'इंटर्नशिप प्रकार',
        allTypes: 'सभी प्रकार',
        paid: 'पेड',
        unpaid: 'अनपेड',
        stipend: 'वृत्ति',
        applicants: 'आवेदक',
        posted: 'पोस्ट किया',
        noInternshipsFound: 'कोई इंटर्नशिप नहीं मिली',
        adjustFilters: 'अधिक परिणाम देखने के लिए अपने फ़िल्टर समायोजित करें',
        applyFilters: 'फ़िल्टर लागू करें',
        
        // Common
        filters: 'फ़िल्टर',
        clearFilters: 'फ़िल्टर साफ़ करें',
        resetFilters: 'फ़िल्टर रीसेट करें',
        salary: 'वेतन',
        minimumSalary: 'न्यूनतम वेतन',
        company: 'कंपनी',
        type: 'प्रकार',
        jobType: 'नौकरी प्रकार',
        fullTime: 'फुल टाइम',
        partTime: 'पार्ट टाइम',
        contract: 'कॉन्ट्रैक्ट',
        gig: 'गिग',
        remote: 'रिमोट',
        onsite: 'ऑनसाइट',
        hybrid: 'हाइब्रिड',
        
        // Landing Page
        heroTagline: 'प्रतिभा को अवसर से जोड़ना',
        heroTitle1: 'नौकरी पाएं. सत्यापित होएं.',
        heroTitle2: 'आगे बढ़ें.',
        heroSubtitle: 'ग्रामीण प्रतिभा के लिए भारत का पहला ब्लॉकचेन-सत्यापित रोजगार मंच. शीर्ष नियोक्ताओं से जुड़ें और अपने कौशल तुरंत साबित करें.',
        jobSeeker: 'मैं नौकरी तलाशने वाला हूं',
        startLearningNow: 'अभी सीखना शुरू करें',
        governmentVerified: 'सरकार सत्यापित',
        candidates10L: '10L+ उम्मीदवार',
        youthUnaware: 'युवा मेल खाती नौकरियों से अनजान',
        verifiedProfiles: 'सत्यापित प्रोफ़ाइल',
        corporatePartners: 'कॉर्पोरेट भागीदार',
        whyChoose: 'SkillBridge क्यों चुनें?',
        bridgingGap: 'प्रतिभा और अवसर के बीच की खाई को पाटना.',
        verifiedCredentialsTitle: 'सत्यापित प्रमाणपत्र',
        verifiedCredentialsDesc: 'आपके कौशल और शिक्षा ब्लॉकचेन पर सत्यापित हैं. अब नकली रिज्यूमे नहीं.',
        skillGapAnalysisTitle: 'कौशल अंतर विश्लेषण',
        skillGapAnalysisDesc: 'हमारे AI मूल्यांकन से जानें कि आपके सपनों की नौकरी पाने के लिए आपको कौन से कौशल चाहिए.',
        instantMatchingTitle: 'तुरंत मिलान',
        instantMatchingDesc: 'हमारा AI आपको वह नौकरियां दिखाता है जो आपके प्रोफ़ाइल से पूरी तरह मेल खाती हैं. एक क्लिक में आवेदन करें.',
        microLearningTitle: 'माइक्रो लर्निंग से कौशल मास्टर करें',
        microLearningSubtitle: 'छोटे पाठों में नए कौशल सीखें. घंटों के बजाय मिनटों में मूल बातें मास्टर करें.',
        lessonDuration: '5-15 मिनट के पाठ',
        lessonDurationDesc: 'छोटे, केंद्रित पाठ जो आपके व्यस्त शेड्यूल में फ़िट होते हैं',
        techModules: '22+ तकनीकी मॉड्यूल',
        techModulesDesc: 'AI, मशीन लर्निंग, वेब डेव, साइबर सुरक्षा और अधिक',
        earnBadges: 'अंक और बैज अर्जित करें',
        earnBadgesDesc: 'अपनी प्रगति को ट्रैक करें और अपनी उपलब्धियां प्रदर्शित करें',
        freeSelfPaced: 'मुफ़्त • स्व-गति • प्रमाणपत्र तैयार',
        readyCareer: 'अपना करियर शुरू करने के लिए तैयार हैं?',
        joinThousands: 'आज अपने भविष्य को सुरक्षित करने वाले हजारों लोगों के साथ जुड़ें.',
        goToDashboard: 'डैशबोर्ड पर जाएं',
        createProfile: 'मुफ़्त प्रोफ़ाइल बनाएं',
        opportunitiesNear: 'आपके पास के अवसर',
        studentTitle: 'मैं बनना चाहता हूं...',
        student: 'छात्र',
        selectInterest: 'रुचि क्षेत्र चुनें',
        interestHint: 'ऑटोमोटिव, इलेक्ट्रॉनिक्स जैसे रुचि क्षेत्र.',
        findCourse: 'कोर्स खोजें',
        exploreTitle: 'मैं खोजना चाहता हूं...',
        opportunities: 'अवसर',
        searchJobExchange: 'जॉब एक्सचेंज खोजें',
        opportunitiesHint: 'जॉब एक्सचेंज, शिक्षुता और उद्यमिता के अवसर',
        findJob: 'नौकरी खोजें',
        notSure: 'पक्का नहीं',
        whereBegin: 'कहां से शुरू करें?',
        guidanceSubtitle: 'कुछ सरल प्रश्नों के उत्तर दें और हम आपकी मदद करेंगे.',
        educationLevelQuestion: 'आपका उच्चतम शिक्षा स्तर क्या है?',
        selectEducation: 'शिक्षा चुनें',
        next: 'अगला',
        
        // Login & Auth
        welcomeBack: 'वापस स्वागत है',
        loginSubtitle: 'अपने सत्यापित प्रोफ़ाइल तक पहुंचने के लिए लॉगिन करें',
        email: 'ईमेल',
        password: 'पासवर्ड',
        rememberMe: 'मुझे याद रखें',
        forgotPassword: 'पासवर्ड भूल गए?',
        loginButton: 'लॉगिन',
        noAccount: 'खाता नहीं है?',
        signUp: 'साइन अप करें',
        getStarted: 'स्किलब्रिज के साथ शुरू करें',
        registerNow: 'अभी रजिस्टर करें',
        alreadyHaveAccount: 'पहले से खाता है?',
        name: 'पूरा नाम',
        phone: 'फोन नंबर',
        confirmPassword: 'पासवर्ड की पुष्टि करें',
        iAgree: 'मैं सहमत हूँ',
        termsAndConditions: 'नियम और शर्तें',
        and: 'और',
        privacyPolicy: 'गोपनीयता नीति',
        
        // Dashboard
        welcome: 'स्वागत',
        welcomeBack2: 'वापस स्वागत है',
        dashboard: 'डैशबोर्ड',
        careerProgress: 'आज आपकी करियर प्रगति यहां है',
        profileCompletion: 'प्रोफ़ाइल पूर्णता',
        complete: 'पूर्ण',
        topJobMatches: 'शीर्ष नौकरी मिलान',
        viewAllJobs: 'सभी नौकरियां देखें',
        myCredentials: 'मेरे प्रमाण पत्र',
        recentActivity: 'हाल की गतिविधि',
        recommendedForYou: 'आपके लिए अनुशंसित',
        skillsOverview: 'कौशल अवलोकन',
        viewSkillGap: 'स्किल गैप देखें',
        
        // Profile Setup
        profileSetupTitle: 'अपना प्रोफ़ाइल पूरा करें',
        profileSetupSubtitle: 'व्यक्तिगत नौकरी मिलान पाने के लिए हमें अपने बारे में बताएं',
        personalInformation: 'व्यक्तिगत जानकारी',
        contactInformation: 'संपर्क जानकारी',
        address: 'पता',
        city: 'शहर',
        state: 'राज्य',
        pincode: 'पिनकोड',
        education: 'शिक्षा',
        highestQualification: 'उच्चतम योग्यता',
        fieldOfStudy: 'अध्ययन का क्षेत्र',
        institution: 'संस्था',
        yearOfPassing: 'उत्तीर्ण वर्ष',
        skills: 'कौशल',
        addSkills: 'अपने कौशल जोड़ें',
        experience: 'अनुभव',
        yearsOfExperience: 'अनुभव के वर्ष',
        currentCompany: 'वर्तमान कंपनी',
        jobTitle: 'नौकरी का शीर्षक',
        saveChanges: 'परिवर्तन सहेजें',
        cancel: 'रद्द करें',
        skip: 'छोड़ें',
        skipForNow: 'अभी के लिए छोड़ें',
        back: 'वापस',
        continue: 'जारी रखें',
        
        // Resume Upload
        uploadResume: 'रिज्यूमे अपलोड करें',
        uploadResumeTitle: 'अपना रिज्यूमे अपलोड करें',
        uploadResumeSubtitle: 'AI-संचालित कौशल विश्लेषण और व्यक्तिगत सिफारिशों के लिए PDF प्रारूप में अपना रिज्यूमे अपलोड करें।',
        chooseFile: 'PDF फाइल चुनें',
        dragDropHere: 'या यहां खींचें और छोड़ें',
        maxFileSize: 'अधिकतम फाइल साइज: 5MB',
        changeFile: 'फाइल बदलें',
        resumeUploadedSuccess: 'रिज्यूमे सफलतापूर्वक अपलोड किया गया!',
        analyzingResume: 'आपके रिज्यूमे का AI से विश्लेषण किया जा रहा है...',
        dragDropResume: 'अपना रिज्यूमे यहां खींचें और छोड़ें',
        or: 'या',
        browseFiles: 'फाइलें ब्राउज़ करें',
        fileRequirements: 'समर्थित प्रारूप: PDF (अधिकतम 5MB)',
        uploading: 'अपलोड हो रहा है',
        analyzing: 'विश्लेषण हो रहा है',
        uploadSuccess: 'रिज्यूमे सफलतापूर्वक अपलोड किया गया!',
        uploadFailed: 'रिज्यूमे अपलोड विफल रहा',
        analysisComplete: 'विश्लेषण पूर्ण',
        uploadAndAnalyze: 'अपलोड करें और विश्लेषण करें',
        uploaded: 'अपलोड किया गया',
        skipForNowBtn: 'अभी के लिए छोड़ें',
        whatHappensNext: 'आगे क्या होगा?',
        securelyStored: 'आपका रिज्यूमे Firebase Storage में सुरक्षित रूप से संग्रहीत है',
        aiAnalyzes: 'AI आपके कौशल, अनुभव और शिक्षा का विश्लेषण करता है',
        personalizedRecommendations: 'व्यक्तिगत नौकरी सिफारिशें और स्किल गैप विश्लेषण प्राप्त करें',
        encryptedSecure: 'आपका डेटा एन्क्रिप्टेड और सुरक्षित रूप से संग्रहीत है',
        
        // Learning/Micro Learning
        learningTitle: 'माइक्रो लर्निंग',
        learningSubtitle: 'छोटे पाठों में नए कौशल सीखें',
        allCourses: 'सभी पाठ्यक्रम',
        inProgress: 'प्रगति में',
        completed: 'पूर्ण',
        startCourse: 'पाठ्यक्रम शुरू करें',
        continueLearning: 'सीखना जारी रखें',
        lessons: 'पाठ',
        duration: 'अवधि',
        difficulty: 'कठिनाई',
        beginner: 'शुरुआती',
        intermediate: 'मध्यवर्ती',
        advanced: 'उन्नत',
        enrollNow: 'अभी नामांकन करें',
        certificateAvailable: 'प्रमाणपत्र उपलब्ध',
        
        // Employer Dashboard
        employerPortal: 'नियोक्ता पोर्टल',
        employerSubtitle: 'सत्यापित ग्रामीण प्रतिभा खोजें और नियुक्त करें',
        postJob: 'नौकरी पोस्ट करें',
        activeJobs: 'सक्रिय नौकरियां',
        totalApplicants: 'कुल आवेदक',
        interviewed: 'साक्षात्कार लिया गया',
        hired: 'नियुक्त',
        recentApplicants: 'हाल के आवेदक',
        searchCandidates: 'उम्मीदवारों को खोजें',
        viewProfile: 'प्रोफ़ाइल देखें',
        scheduleInterview: 'साक्षात्कार निर्धारित करें',
        shortlist: 'शॉर्टलिस्ट',
        match: 'मिलान',
        
        // Common Buttons & Actions
        save: 'सहेजें',
        edit: 'संपादित करें',
        delete: 'हटाएं',
        confirm: 'पुष्टि करें',
        yes: 'हाँ',
        no: 'नहीं',
        ok: 'ठीक है',
        close: 'बंद करें',
        submit: 'सबमिट करें',
        apply: 'आवेदन करें',
        download: 'डाउनलोड करें',
        share: 'साझा करें',
        viewDetails: 'विवरण देखें',
        viewAll: 'सभी देखें',
        learnMore: 'और जानें',
        search: 'खोजें',
        loading: 'लोड हो रहा है...',
        error: 'त्रुटि',
        success: 'सफलता',
        tryAgain: 'पुनः प्रयास करें',
        goBack: 'वापस जाएं',
        
        // Messages
        noDataAvailable: 'कोई डेटा उपलब्ध नहीं',
        somethingWentWrong: 'कुछ गलत हुआ',
        pleaseWait: 'कृपया प्रतीक्षा करें...',
        processingRequest: 'आपका अनुरोध संसाधित किया जा रहा है...',
        savedSuccessfully: 'सफलतापूर्वक सहेजा गया',
        updatedSuccessfully: 'सफलतापूर्वक अपडेट किया गया',
        deletedSuccessfully: 'सफलतापूर्वक हटाया गया',
        
        // Skill Gap Dashboard
        skillGapDashboardTitle: 'कौशल अंतर विश्लेषण डैशबोर्ड',
        aiWorkforceInsights: 'AI-संचालित कार्यबल कौशल अंतर्दृष्टि',
        reseedDemoData: 'डेमो डेटा फिर से भरें',
        seeding: 'बोआई...',
        menu: 'मेनू',
        resumeAnalysis: 'रिज्यूमे विश्लेषण',
        analyzed: 'विश्लेषित',
        empty: 'खाली',
        noResumeAnalysisFound: 'कोई रिज्यूमे विश्लेषण नहीं मिला',
        uploadResumeUnlock: 'AI-संचालित कौशल अंतर्दृष्टि और व्यक्तिगत कैरियर सिफारिशें अनलॉक करने के लिए अपना रिज्यूमे अपलोड करें।',
        resumeScore: 'रिज्यूमे स्कोर',
        experienceLevel: 'अनुभव',
        detailedAnalysisResults: 'विस्तृत विश्लेषण परिणाम',
        skillMatchingFor: 'के लिए कौशल मिलान',
        selectedRole: 'चयनित भूमिका',
        matchPercentage: 'मिलान प्रतिशत',
        requiredSkillsPossessed: 'आवश्यक कौशल मौजूद',
        readinessScore: 'तैयारी स्कोर',
        outOf100: '100 अंकों में से',
        gapOverview: 'अंतर अवलोकन',
        critical: 'महत्वपूर्ण',
        moderate: 'मध्यम',
        good: 'अच्छा',
        skillName: 'कौशल नाम',
        required: 'आवश्यक',
        user: 'उपयोगकर्ता',
        status: 'स्थिति',
        recommendedLearningAI: 'अनुशंसित सीखना (AI संचालित)',
        personalizedTutorials: 'आपके कौशल के आधार पर व्यक्तिगत ट्यूटोरियल',
        curatingVideos: 'व्यक्तिगत वीडियो तैयार किया जा रहा है...',
        watchNow: 'अभी देखें',
        tutorial: 'ट्यूटोरियल',
        noVideoRecommendations: 'कोई वीडियो सिफारिश नहीं मिली। व्यक्तिगत सीखने के रास्ते अनलॉक करने के लिए अपना रिज्यूमे अपलोड करें।',
        profileOverview: 'प्रोफाइल अवलोकन',
        lastUpdated: 'अंतिम अपडेट',
        resumeStatus: 'रिज्यूमे स्थिति',
        verified: 'सत्यापित',
        pendingUpload: 'अपलोड लंबित',
        skillScore: 'कौशल स्कोर',
        matchStrength: 'मिलान शक्ति',
        quickActions: 'त्वरित कार्रवाई',
        uploadResumeBtn: 'रिज्यूमे अपलोड करें',
        viewSkillGapReport: 'स्किल गैप रिपोर्ट देखें',
        exploreCourses: 'कोर्स एक्सप्लोर करें',
        tip: 'सुझाव',
        completeCriticalSkills: 'अपनी मैच शक्ति को 40 प्रतिशत तक बढ़ाने के लिए अपनी प्रोफ़ाइल में हाइलाइट की गई महत्वपूर्ण कौशल अंतराल को पूरा करें।',
        authenticating: 'प्रमाणीकरण...',
        loadingDashboard: 'डैशबोर्ड लोड हो रहा है...',
        
        // Resume Upload Page
        chooseFile: 'PDF फ़ाइल चुनें',
        dragDropHere: 'या यहां ड्रैग और ड्रॉप करें',
        maxFileSize: 'अधिकतम फ़ाइल आकार: 5MB',
        changeFile: 'फ़ाइल बदलें',
        analyzingResume: 'आपके रिज्यूमे का AI के साथ विश्लेषण किया जा रहा है...',
        resumeUploadedSuccess: 'रिज्यूमे सफलतापूर्वक अपलोड किया गया!',
        skipForNowBtn: 'अभी के लिए छोड़ें',
        encryptedSecure: 'आपका डेटा एन्क्रिप्ट और सुरक्षित रूप से संग्रहीत है',
        
        // Profile Setup
        interestedDomain: 'रुचि का डोमेन',
        selectDomain: 'अपनी इच्छित नौकरी भूमिका चुनें',
        selectSkills: 'अपने कौशल चूनें',
        selectSkillsHint: 'आपके पास मौजूद या सीखने की इच्छा रखने वाले कौशल चुनें',
        fieldOfInterest: 'रुचि का क्षेत्र',
        enterFieldInterest: 'अपना विशिष्ट रुचि क्षेत्र दर्ज करें',
        experienceLevelLabel: 'अनुभव स्तर',
        selectExperienceLevel: 'अपना अनुभव स्तर चुनें',
        locationLabel: 'पसंदीदा स्थान',
        selectLocation: 'पसंदीदा कार्य स्थान चुनें',
        fresher: 'फ्रेशर',
        junior: 'जूनियर',
        midLevel: 'मिड-लेवल',
        senior: 'वरिष्ठ',
        
        // Basic Info
        fullName: 'पूरा नाम',
        phoneNumber: 'फ़ोन नंबर',
        dateOfBirth: 'जन्म तिथि',
        gender: 'लिंग',
        male: 'पुरुष',
        female: 'महिला',
        other: 'अन्य',
        district: 'जिला',
        selectDistrict: 'जिला चुनें',
        selectState: 'राज्य चुनें',
        selectGender: 'लिंग चुनें',
        basicInfoTitle: 'बुनियादी जानकारी',
        basicInfoSubtitle: 'कृपया अपना व्यक्तिगत विवरण प्रदान करें',
        
        // Validation Messages
        nameRequired: 'पूर्ण नाम आवश्यक है',
        nameMinLength: 'नाम कम से कम 3 वर्णों का होना चाहिए',
        phoneRequired: 'फ़ोन नंबर आवश्यक है',
        invalidPhone: 'एक मान्य 10 अंकों का भारतीय मोबाइल नंबर दर्जकरें',
        invalidEmail: 'एक मान्य ईमेल पता दर्ज करें',
        dobRequired: 'जन्म तिथि आवश्यक है',
        ageRestriction: 'उम्र 18 और 100 वर्ष के बीच होनी चाहिए',
        genderRequired: 'कृपया अपना लिंग चुनें',
        stateRequired: 'कृपया अपना राज्य चुनें',
        districtRequired: 'जिला आवश्यक है',
        domainRequired: 'कृपया अपना इच्छित डोमेन चुनें',
        skillsRequired: 'कृपया कम से कम एक कौशल चुनें',
        fieldRequired: 'कृपया अपनी रुचि का क्षेत्र दर्ज करें'
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('skillbridge_language') || 'en';
    });

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('skillbridge_language', lang);
    };

    const t = (key) => {
        return translations[language][key] || translations.en[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
